import Array_list

print("TEST INT")
arr_int_0 = Array_list.Array_list()
arr_int_1 = Array_list.Array_list(1, 2, 3, 2, 1)
arr_int_2 = Array_list.Array_list(11, 22, 33)

print(arr_int_1.index(3))
print(arr_int_1.count(2))
arr_int_1.append(999)
print(*arr_int_1.data)
arr_int_1.extend(arr_int_2)
print(*arr_int_1.data)
arr_int_1.pop(6)
print(*arr_int_1.data)
arr_int_1.remove(3)
print(*arr_int_1.data)
print(999 in arr_int_1)
arr_int_1 += arr_int_2
print(*arr_int_1.data)
print(len(arr_int_1))
print(arr_int_1[5])
arr_int_1[5] = 1488
print(*arr_int_1.data)
reversed(arr_int_1)
print(*reversed(arr_int_1))
arr_int_1.clear()
print(arr_int_1.data)

print()
print("TEST FLOAT")
arr_float_0 = Array_list.Array_list()
arr_float_1 = Array_list.Array_list(1.1, 2.2, 3.3, 1.1, 5.5)
arr_float_2 = Array_list.Array_list(0.1, 0.2, 0.3, 0.4)

print(arr_float_1.index(5.5))
print(arr_float_1.count(1.1))
arr_float_1.append(999.999)
print(*arr_float_1.data)
arr_float_1.extend(arr_float_2)
print(*arr_float_1.data)
arr_float_1.pop(2)
print(*arr_float_1.data)
arr_float_1.remove(0.2)
print(*arr_float_1.data)
print(999.1 in arr_float_1)
arr_float_1 += arr_float_2
print(*arr_float_1.data)
print(len(arr_float_1))
print(arr_float_1[4])
arr_float_1[4] = 4.20
print(*arr_float_1.data)
print(*reversed(arr_float_1))
arr_float_1.clear()
print(arr_float_1.data)

print()
print("TEST STR")
arr_str_0 = Array_list.Array_list()
arr_str_1 = Array_list.Array_list('a', 'b', 'c', 'a', 'a', 'a')
arr_str_2 = Array_list.Array_list('Z', 'Y', 'X')
print(arr_str_1.index('c'))
print(arr_str_1.count('a'))
arr_str_1.append('L')
print(*arr_str_1.data)
arr_str_1.extend(arr_str_2)
print(*arr_str_1.data)
arr_str_1.pop(6)
print(*arr_str_1.data)
arr_str_1.remove('a')
print(*arr_str_1.data)
print('Z' in arr_str_1)
arr_str_1 += arr_str_2
print(*arr_str_1.data)
print(len(arr_str_1))
print(arr_str_1[5])
arr_str_1[3] = '@'
print(*arr_str_1.data)
print(*reversed(arr_str_1))
arr_str_1.clear()
print(arr_str_1.data)
